kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      name: chat-app
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: iemafzal/frontend:v1
        ports:
        - containerPort: 80
