apiVersion: v1
kind: Service
metadata:
  name: {{ include "three-tier.fullname" . }}-backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http