apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chat-app.fullname" . }}-frontend
spec:
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chat-app.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
