apiVersion: v2
name: chat-app
description: Simple three tier application (frontend, backend, database)
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Avinash
    email: avinash@example.com